version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  node: circleci/node@4.3.0

filters: &filters
  tags:
    only: /.*/

workflows:
  # Prior to producing a development orb (which requires credentials) basic validation, linting, and even unit testing can be performed.
  # This workflow will run on every commit
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - orb-tools/review

      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: monito/license-checker
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review]
          filters: *filters
